/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.GerenciarEmpregado;
import model.ParametroINSS;
import model.Empregado;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class EditarEmpregadoGUI extends javax.swing.JFrame {

    GerenciarEmpregado gerEmp = new GerenciarEmpregado();
    Empregado e;
    /**
     * Creates new form EditarEmpregadoGUI
     */
    public EditarEmpregadoGUI(int id) {
        initComponents();
        textSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.##"))));
        e = gerEmp.selecionarEmpregado(id);
        textCodigoEmpregado.setText(Integer.toString(e.getCodigoEmpregado()));
        textNomeEmpregado.setText(e.getNomeEmpregado());
        textSetor.setText(e.getSetor());
        System.out.println(e.getSalarioBruto());
        textSalario.setText(Double.toString(e.getSalarioBruto()).replace(".", ","));
        labelValorCalculado.setText("R$ " + e.getRecInss());
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCodigoEmpregado = new javax.swing.JLabel();
        labelNomeEmpregado = new javax.swing.JLabel();
        labelSetor = new javax.swing.JLabel();
        labelSalarioBruto = new javax.swing.JLabel();
        labelRecolhimento = new javax.swing.JLabel();
        textCodigoEmpregado = new javax.swing.JTextField();
        textNomeEmpregado = new javax.swing.JTextField();
        textSetor = new javax.swing.JTextField();
        buttonCalcular = new javax.swing.JButton();
        labelValorCalculado = new javax.swing.JLabel();
        buttonApresentar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        textSalario = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Empregado");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Editar"), "Editar"));

        labelCodigoEmpregado.setText("Código do Empregado");

        labelNomeEmpregado.setText("Nome do Empregado");

        labelSetor.setText("Setor");

        labelSalarioBruto.setText("Salário Bruto");

        labelRecolhimento.setText("Recolhimento");

        buttonCalcular.setText("Calcular Recolhimento INSS");
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });

        labelValorCalculado.setText("R$");

        buttonApresentar.setText("Voltar");
        buttonApresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApresentarActionPerformed(evt);
            }
        });

        buttonCadastrar.setText("Salvar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelRecolhimento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSalarioBruto)
                            .addComponent(labelNomeEmpregado)
                            .addComponent(labelCodigoEmpregado)
                            .addComponent(labelSetor))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelValorCalculado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCodigoEmpregado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNomeEmpregado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textSetor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSalario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonApresentar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCadastrar)))
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelCodigoEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(labelNomeEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(textCodigoEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(textNomeEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(textSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(buttonCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelValorCalculado)
                            .addComponent(labelRecolhimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonApresentar)
                            .addComponent(buttonCadastrar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        try {
            //Envia pedido para cadastro de Uusuário

            e.setCodigoEmpregado(Integer.parseInt(textCodigoEmpregado.getText()));
            e.setNomeEmpregado(textNomeEmpregado.getText());
            String temp = textSalario.getText().replace(".", "");
            temp = temp.replace(",", ".");
            e.setSalarioBruto(Double.parseDouble(temp));
            e.setSetor(textSetor.getText());
            e.setRecInss((Double.parseDouble(temp)));

            ParametroINSS pin = new ParametroINSS();
            e.setRecInss(pin.calcularInss(Double.parseDouble(temp)));

            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Empregado atualizado com sucesso!");

            GerenciarEmpregadosGUI gerEmp = new GerenciarEmpregadosGUI();
            gerEmp.setVisible(true);
            dispose();

        } catch (Exception e) {
            JOptionPane optionPane = new JOptionPane("Erro! Confira os dados e tente novamente!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Erro");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
        }

    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonApresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApresentarActionPerformed
        // TODO add your handling code here:
        GerenciarEmpregadosGUI gerEmp = new GerenciarEmpregadosGUI();
        gerEmp.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonApresentarActionPerformed

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed

        try {
            //e = new Empregado();
            Empregado empTemp = new Empregado();

            empTemp.setCodigoEmpregado(Integer.parseInt(textCodigoEmpregado.getText()));
            empTemp.setNomeEmpregado(textNomeEmpregado.getText());
            String temp = textSalario.getText().replace(".", "");
            temp = temp.replace(",", ".");
            empTemp.setSalarioBruto(Double.parseDouble(temp));
            empTemp.setSetor(textSetor.getText());

            ParametroINSS pin = new ParametroINSS();
            labelValorCalculado.setText("R$ " + pin.calcularInss(Double.parseDouble(temp)));
            empTemp.setRecInss(pin.calcularInss(Double.parseDouble(temp)));

        } catch (Exception e) {
            JOptionPane optionPane = new JOptionPane("Erro! Confira os dados e tente novamente!", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Erro");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);

        }
    }//GEN-LAST:event_buttonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregadoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApresentar;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCodigoEmpregado;
    private javax.swing.JLabel labelNomeEmpregado;
    private javax.swing.JLabel labelRecolhimento;
    private javax.swing.JLabel labelSalarioBruto;
    private javax.swing.JLabel labelSetor;
    private javax.swing.JLabel labelValorCalculado;
    private javax.swing.JTextField textCodigoEmpregado;
    private javax.swing.JTextField textNomeEmpregado;
    private javax.swing.JFormattedTextField textSalario;
    private javax.swing.JTextField textSetor;
    // End of variables declaration//GEN-END:variables
}
